# Generated by Django 5.2.7 on 2025-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='NRC',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
