# Generated by Django 5.2.7 on 2025-10-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_nrc'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
