# Generated by Django 5.2.7 on 2026-01-21 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_alter_semester_semester_name'),
        ('Students', '0003_alter_studentprofile_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.intake'),
        ),
    ]
