# Generated by Django 5.2.7 on 2025-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='student_profiles/'),
        ),
    ]
