# Generated by Django 5.2.7 on 2026-01-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_studentprofile_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='student_profiles/'),
        ),
    ]
