# Generated by Django 5.2.7 on 2025-10-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student',
            new_name='student_id',
        ),
    ]
