# Generated by Django 5.2.7 on 2025-11-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_rename_student_studentprofile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='student_profiles/'),
        ),
    ]
