# Generated by Django 5.2.7 on 2026-01-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='qrcodes/'),
        ),
    ]
