# Generated by Django 5.2.7 on 2025-11-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_alter_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(default='fallback.png', upload_to='student_profiles/'),
        ),
    ]
