# Generated by Django 5.2.7 on 2026-01-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Psychologist', 'Pyschologist'), ('Librarian', 'Librarian'), ('Clinical Instructor', 'Clinical Instructor'), ('Accountant', 'Accountant')], max_length=30, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='fallback.png', upload_to='staff_profiles/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('employment_status', models.CharField(choices=[('FullTime', 'FullTime'), ('PartTime', 'PartTime')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
