# Generated by Django 5.2.7 on 2026-01-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
        ('Fees', '0002_ledgerentry_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='year_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.yearofstudy'),
        ),
    ]
