# Generated by Django 5.2.7 on 2026-01-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0003_fee_year_of_study'),
        ('Students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Fees.studentaccount'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='Students.student'),
        ),
    ]
