# Generated by Django 5.2.7 on 2026-01-13 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0004_alter_payment_account_alter_studentaccount_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fees.fee'),
        ),
    ]
