# Generated by Django 5.2.7 on 2026-01-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0005_invoice_description_alter_invoice_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedfee',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fees.fee'),
        ),
    ]
