# Generated by Django 5.2.7 on 2026-01-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0006_alter_appliedfee_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('Tuition', 'Tuition'), ('Registration', 'Registration'), ('Examination', 'Exam'), ('Laboratory', 'Lab'), ('NCZ', 'Ncz')], max_length=30),
        ),
    ]
