# Generated by Django 6.0.1 on 2026-01-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0007_alter_fee_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
