# Generated by Django 5.2.7 on 2026-01-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_yearofstudy_intake_sessionyear_intake_semester'),
        ('Fees', '0009_alter_invoice_id_alter_ledgerentry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='year_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.yearofstudy'),
        ),
    ]
