# Generated by Django 5.2.7 on 2026-01-24 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0007_sessionyear_semester'),
        ('Fees', '0010_alter_fee_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedfee',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.semester'),
        ),
    ]
