# Generated by Django 5.2.7 on 2026-01-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0008_rename_semester_sessionyear_semester'),
        ('Fees', '0011_appliedfee_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appliedfee',
            unique_together={('account', 'fee', 'semester', 'is_reversed')},
        ),
    ]
