# Generated by Django 5.2.7 on 2025-11-14 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0001_initial'),
        ('Courses', '0002_alter_courses_course_code'),
        ('Students', '0005_rename_student_studentprofile_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('registraion_date', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(related_name='registrations', to='Courses.courses')),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.sessionyear')),
                ('student_id', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
                ('year_of_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.yearofstudy')),
            ],
        ),
    ]
