# Generated by Django 5.2.7 on 2026-01-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0001_initial'),
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='registration_qr_codes')),
                ('fees_invoiced', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(related_name='registrations', to='Courses.courses')),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_years', to='Academics.sessionyear')),
            ],
        ),
    ]
