# Generated by Django 5.2.7 on 2025-11-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registraion_date',
            new_name='registration_date',
        ),
    ]
