# Generated by Django 5.2.7 on 2026-01-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0002_initial'),
        ('Registration', '0001_initial'),
        ('Students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='student_id',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='Students.student'),
        ),
        migrations.AddField(
            model_name='registration',
            name='year_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.yearofstudy'),
        ),
    ]
