# Generated by Django 5.2.7 on 2025-11-21 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_rename_registraion_date_registration_registration_date'),
        ('Students', '0005_rename_student_studentprofile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student_id',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='Students.student'),
        ),
    ]
