# Generated by Django 5.2.7 on 2025-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_alter_registration_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='registration_qr_codes'),
        ),
    ]
