# Generated by Django 5.2.7 on 2026-01-20 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_alter_semester_semester_name'),
        ('Registration', '0003_alter_registration_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.intake'),
        ),
    ]
