# Generated by Django 5.2.7 on 2026-01-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_alter_semester_semester_name'),
        ('Registration', '0004_registration_intake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='intake',
        ),
        migrations.AddField(
            model_name='registration',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.semester'),
        ),
    ]
