# Generated by Django 5.2.7 on 2025-12-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
        ('Registration', '0004_registration_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='session_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_years', to='Academics.sessionyear'),
        ),
    ]
