# Generated by Django 5.2.7 on 2026-01-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
        ('Programs', '0001_initial'),
        ('Staff', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.staff'),
        ),
        migrations.AddField(
            model_name='courses',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='Programs.programs'),
        ),
        migrations.AddField(
            model_name='courses',
            name='year_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.yearofstudy'),
        ),
    ]
