# Generated by Django 5.2.4 on 2025-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
