# Generated by Django 5.2.7 on 2026-01-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_yearofstudy_intake_sessionyear_intake_semester'),
        ('Courses', '0002_initial'),
        ('Fees', '0010_alter_fee_year_of_study'),
        ('Registration', '0003_alter_registration_year_of_study'),
        ('Students', '0003_alter_studentprofile_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='year_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.yearofstudy'),
        ),
        migrations.DeleteModel(
            name='YearOfStudy',
        ),
    ]
