# Generated by Django 5.2.7 on 2026-01-20 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0003_alter_semester_semester_name'),
        ('Courses', '0003_alter_courses_year_of_study_delete_yearofstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='practical_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.semester'),
        ),
        migrations.AddField(
            model_name='courses',
            name='theory_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
