# Generated by Django 5.2.7 on 2025-11-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_courses_program_id'),
        ('Staff', '0002_alter_staffprofile_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='date_adde',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='courses',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.staff'),
        ),
    ]
