# Generated by Django 5.2.7 on 2025-11-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
