# Generated by Django 5.2.7 on 2026-01-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departments', '0002_initial'),
        ('Programs', '0001_initial'),
        ('Staff', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.staff'),
        ),
        migrations.AddField(
            model_name='programs',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='Departments.department'),
        ),
    ]
