# Generated by Django 5.2.7 on 2025-11-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_alter_programs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='program_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
