# Generated by Django 5.2.7 on 2025-11-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('Programs', '0003_alter_programs_program_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='Departments.department'),
        ),
    ]
