# Generated by Django 5.2.7 on 2025-11-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0004_alter_programs_department_id'),
        ('Staff', '0002_alter_staffprofile_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.staff'),
        ),
    ]
