# Generated by Django 5.2.7 on 2026-01-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_yearofstudy_intake_sessionyear_intake_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second')], max_length=20, null=True, unique=True),
        ),
    ]
