# Generated by Django 5.2.7 on 2026-01-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0003_alter_semester_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(choices=[('semester_1', 'First'), ('semester_2', 'Second')], max_length=20, null=True, unique=True),
        ),
    ]
