# Generated by Django 5.2.7 on 2026-01-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_alter_semester_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearofstudy',
            name='year_title',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=50, null=True, unique=True),
        ),
    ]
