# Generated by Django 5.2.7 on 2026-01-24 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0006_alter_yearofstudy_year_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyear',
            name='Semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester', to='Academics.semester'),
        ),
    ]
