# Generated by Django 5.2.7 on 2026-01-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0007_sessionyear_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionyear',
            old_name='Semester',
            new_name='semester',
        ),
    ]
