# Generated by Django 5.2.7 on 2025-11-06 18:04

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0002_alter_courses_course_code'),
        ('Programs', '0003_alter_programs_program_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Information',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1925, 11, 6), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2009, 11, 6), message='Must be at least 16 years old')])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('NRC', models.CharField(max_length=20, unique=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('city_of_residence', models.CharField(blank=True, max_length=50, null=True)),
                ('deposit_slip', models.FileField(upload_to='slips/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='profile_picture', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Programs.programs')),
                ('year_of_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.yearofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='Application_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application_System.general_information')),
            ],
        ),
        migrations.CreateModel(
            name='Next_of_Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('addmission_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application_System.general_information')),
            ],
        ),
        migrations.CreateModel(
            name='School_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('SECONDARY', 'Secondary_School_Certificate'), ('DIPLOMA', 'Diploma'), ('DEGREE', 'Degree'), ('ADVANCED_CERTIFICATE', 'Advanced_Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('certificate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('year_of_completion', models.PositiveIntegerField(blank=True, null=True)),
                ('addmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application_System.general_information')),
            ],
        ),
    ]
