# Generated by Django 5.2.7 on 2025-11-04 11:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Information',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1925, 11, 4), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2009, 11, 4), message='Must be at least 16 years old')])),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('NRC', models.CharField(max_length=20, unique=True)),
                ('scan_of_slip', models.FileField(upload_to='slips/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('date_of_application', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.staff')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application_System.general_information')),
            ],
        ),
        migrations.CreateModel(
            name='School_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('SECONDARY', 'Secondary_School_Certificate'), ('DIPLOMA', 'Diploma'), ('DEGREE', 'Degree'), ('ADVANCED_CERTIFICATE', 'Advanced_Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('certificate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('scan_copy', models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('addmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application_System.general_information')),
            ],
        ),
    ]
