# Generated by Django 5.2.7 on 2026-01-08 20:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10)),
                ('grade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='General_Information',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1926, 1, 8), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2010, 1, 8), message='Must be at least 16 years old')])),
                ('NRC', models.CharField(max_length=20, unique=True)),
                ('NRC_scan', models.FileField(blank=True, null=True, upload_to='nrc_scans/')),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city_of_residence', models.CharField(blank=True, max_length=50, null=True)),
                ('disability', models.CharField(default='No', max_length=5)),
                ('disability_desc', models.CharField(blank=True, max_length=15, null=True)),
                ('deposit_slip', models.FileField(blank=True, null=True, upload_to='slips/')),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('passport_photo', models.ImageField(default='fallback.png', upload_to='profile_picture', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='Next_of_Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('NK_address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('SECONDARY', 'Secondary_School_Certificate'), ('DIPLOMA', 'Diploma'), ('DEGREE', 'Degree'), ('ADVANCED_CERTIFICATE', 'Advanced_Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('certificate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate', models.FileField(upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('year_of_completion', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
