# Generated by Django 5.2.7 on 2025-11-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_certificate',
            name='addmission',
        ),
        migrations.DeleteModel(
            name='Application_Status',
        ),
        migrations.DeleteModel(
            name='General_Information',
        ),
        migrations.DeleteModel(
            name='School_Certificate',
        ),
    ]
