# Generated by Django 5.2.7 on 2025-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
