# Generated by Django 5.2.7 on 2026-01-08 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Application_System', '0001_initial'),
        ('Programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application_status',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='general_information',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='Programs.programs'),
        ),
        migrations.AddField(
            model_name='certificateresults',
            name='admission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Application_System.general_information'),
        ),
        migrations.AddField(
            model_name='application_status',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='Application_System.general_information'),
        ),
        migrations.AddField(
            model_name='next_of_kin',
            name='addmission_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='Application_System.general_information'),
        ),
        migrations.AddField(
            model_name='school_certificate',
            name='addmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certficate', to='Application_System.general_information'),
        ),
    ]
