# Generated by Django 5.2.7 on 2026-01-09 15:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateresults',
            name='subject_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1926, 1, 9), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2010, 1, 9), message='Must be at least 16 years old')]),
        ),
    ]
