# Generated by Django 5.2.7 on 2025-11-10 15:52

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0002_alter_general_information_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1925, 11, 10), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2009, 11, 10), message='Must be at least 16 years old')]),
        ),
        migrations.CreateModel(
            name='CertificateResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10)),
                ('grade', models.PositiveIntegerField()),
                ('admission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application_System.general_information')),
            ],
        ),
    ]
