# Generated by Django 5.2.7 on 2025-11-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0003_alter_general_information_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_information',
            name='disability',
            field=models.CharField(default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='general_information',
            name='disability_desc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='application_status',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='Application_System.general_information'),
        ),
        migrations.AlterField(
            model_name='certificateresults',
            name='admission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Application_System.general_information'),
        ),
        migrations.AlterField(
            model_name='next_of_kin',
            name='addmission_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='Application_System.general_information'),
        ),
        migrations.AlterField(
            model_name='school_certificate',
            name='addmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certficate', to='Application_System.general_information'),
        ),
    ]
