# Generated by Django 5.2.7 on 2025-11-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_status',
            name='reviewed_by',
        ),
    ]
