# Generated by Django 5.2.7 on 2025-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0004_general_information_disability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='next_of_kin',
            name='NK_address',
            field=models.TextField(null=True),
        ),
    ]
