# Generated by Django 5.2.7 on 2025-11-05 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0004_remove_application_status_reviewed_by'),
        ('Courses', '0002_alter_courses_course_code'),
        ('Programs', '0003_alter_programs_program_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_information',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Programs.programs'),
        ),
        migrations.AddField(
            model_name='general_information',
            name='year_of_study',
            field=models.ForeignKey(blank=True, default=uuid.UUID('6d369157-020f-414c-846b-afef3fce01dd'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.yearofstudy'),
        ),
    ]
