# Generated by Django 5.2.7 on 2025-11-11 19:51

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0005_next_of_kin_nk_address'),
        ('Programs', '0003_alter_programs_program_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1925, 11, 11), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2009, 11, 11), message='Must be at least 16 years old')]),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='Programs.programs'),
        ),
    ]
