# Generated by Django 5.2.7 on 2025-11-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0005_general_information_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_information',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
