# Generated by Django 5.2.7 on 2025-11-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0006_general_information_gender'),
        ('Courses', '0002_alter_courses_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='year_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.yearofstudy'),
        ),
    ]
