# Generated by Django 5.2.7 on 2025-11-12 18:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0006_alter_general_information_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1925, 11, 12), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2009, 11, 12), message='Must be at least 16 years old')]),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='passport_photo',
            field=models.ImageField(default='fallback.png', upload_to='profile_picture', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
