# Generated by Django 5.2.7 on 2025-11-06 16:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0007_alter_general_information_year_of_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general_information',
            old_name='scan_of_slip',
            new_name='deposit_slip',
        ),
        migrations.AddField(
            model_name='general_information',
            name='city_of_residence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='general_information',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1925, 11, 6), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2009, 11, 6), message='Must be at least 16 years old')]),
        ),
    ]
