# Generated by Django 5.2.7 on 2025-11-06 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0008_rename_scan_of_slip_general_information_deposit_slip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_information',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
