# Generated by Django 5.2.7 on 2025-11-15 08:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0008_alter_general_information_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1925, 11, 15), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2009, 11, 15), message='Must be at least 16 years old')]),
        ),
        migrations.AlterField(
            model_name='next_of_kin',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
