# Generated by Django 5.2.7 on 2026-01-20 23:39

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_alter_semester_semester_name'),
        ('Application_System', '0009_alter_general_information_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_information',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.intake'),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1926, 1, 21), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2010, 1, 21), message='Must be at least 16 years old')]),
        ),
    ]
