# Generated by Django 5.2.7 on 2025-11-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0009_general_information_passport_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Next_of_Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('addmission_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Application_System.general_information')),
            ],
        ),
    ]
