# Generated by Django 5.2.7 on 2026-01-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0013_alter_general_information_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
