# Generated by Django 5.2.7 on 2025-11-27 22:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0016_application_status_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1925, 11, 28), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2009, 11, 28), message='Must be at least 16 years old')]),
        ),
    ]
