# Generated by Django 5.2.7 on 2025-12-07 12:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0020_alter_general_information_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_information',
            name='NRC_scan',
            field=models.FileField(blank=True, null=True, upload_to='nrc_scans/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1925, 12, 7), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2009, 12, 7), message='Must be at least 16 years old')]),
        ),
    ]
