# Generated by Django 5.2.7 on 2026-01-02 09:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_System', '0026_alter_general_information_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='NRC_scan',
            field=models.FileField(blank=True, null=True, upload_to='nrc_scans/'),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1926, 1, 2), message='Date of birth cannot be more than 100 years ago'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2010, 1, 2), message='Must be at least 16 years old')]),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='deposit_slip',
            field=models.FileField(blank=True, null=True, upload_to='slips/'),
        ),
    ]
